apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: proxy-ingress
spec:
  rules:
  - http:
      paths:
      -  path: /
         backend:
          serviceName: proxy-public
          servicePort: 80
