# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: "50acbef66d21b6d944c13974ad3e207609376e1d09d4c79e99453472645bc639"

  # comment this out if not using github authentication#  auth:
    type: github
    github:
      clientId: "02c0cb459b3af43feb05"
      clientSecret: "5eef19da6249eaecd1ee1390f24d3d229688c713"
      callbackUrl: "http://54.245.212.110/hub/oauth_callback"
#    admin:
#      access: true
#      users:
#        - admin_user_1
#        - admin_user_2
